"""AKShare 本地类型存根。

AKShare 未随包发布类型标记，strict 模式下接口返回值会退化为 Unknown
并向调用方扩散。此处仅声明本目录脚本实际调用的接口，新增静态调用时需
同步补充声明；动态调用（getattr 传变量名）天然退化为 Any，不受影响。
"""

from typing import Any

from pandas import DataFrame

def search(
    query: str,
    limit: int = ...,
    category: str | None = ...,
    documented_only: bool = ...,
) -> DataFrame: ...
def list_categories() -> DataFrame: ...
def interface_info(name: str) -> dict[str, Any]: ...
def fund_name_em() -> DataFrame: ...
def fund_portfolio_hold_em(symbol: str = ..., date: str = ...) -> DataFrame: ...
def fund_portfolio_industry_allocation_em(
    symbol: str = ..., date: str = ...
) -> DataFrame: ...
def stock_news_em(symbol: str = ...) -> DataFrame: ...
def stock_fund_flow_industry(symbol: str = ...) -> DataFrame: ...
def stock_fund_flow_concept(symbol: str = ...) -> DataFrame: ...
def stock_fund_flow_individual(symbol: str = ...) -> DataFrame: ...
def stock_zh_index_spot_sina() -> DataFrame: ...
